all:
  children:
    garrett_fleet:
      hosts:
        icinga2:
          ansible_host: 10.79.20.40
          ansible_user: root
        postgres1:
          ansible_host: 10.79.20.50
          ansible_user: root
        k3s1:
          ansible_host: 10.79.20.60
          ansible_user: root
        k3s2:
          ansible_host: 10.79.20.61
          ansible_user: root
        k3s3:
          ansible_host: 10.79.20.62
          ansible_user: root
      vars:
        ansible_python_interpreter: /usr/bin/python3
    icinga_hosts:
      hosts:
        icinga2:
    postgres_hosts:
      hosts:
        postgres1:
    k3s_server_hosts:
      hosts:
        k3s1:
    k3s_agent_hosts:
      hosts:
        k3s2:
        k3s3:
    k3s_hosts: # parent group covering the whole cluster - used by app-deploy
      children:
        k3s_server_hosts:
        k3s_agent_hosts:
